export default {
  index: {
    title: 'Inicio',
    display: 'hidden',
  },
  mateo: 'Mateo',
  marcos: 'Marcos',
  lucas: 'Lucas',
  juan: 'Juan',
  hechos: 'Hechos',
  romanos: 'Romanos',
  'corintios-1': '1 Corintios',
  'corintios-2': '2 Corintios',
  galatas: 'Gálatas',
  efesios: 'Efesios',
  filipenses: 'Filipenses',
  colosenses: 'Colosenses',
  'tesalonicenses-1': '1 Tesalonicenses',
  'tesalonicenses-2': '2 Tesalonicenses',
  'timoteo-1': '1 Timoteo',
  'timoteo-2': '2 Timoteo',
  tito: 'Tito',
  filemon: 'Filemón',
  hebreos: 'Hebreos',
  santiago: 'Santiago',
  'pedro-1': '1 Pedro',
  'pedro-2': '2 Pedro',
  'juan-1': '1 Juan',
  'juan-2': '2 Juan',
  'juan-3': '3 Juan',
  judas: 'Judas',
  apocalipsis: 'Apocalipsis',
}
